import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata = {
  title: 'PixelPunk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <ClerkProvider>

          <html lang="en">
          <body>
          {children}
          </body>
          </html>

      </ClerkProvider>

  )
}


